import Foundation

/// Persistent user identity store.
///
/// - `anonymousId` is generated on first run and regenerated by `reset()`.
/// - `externalId` is set via `identify(userId:)` and cleared on `reset()`.
final class IdentityStore {
    struct Snapshot: Codable, Equatable {
        var anonymousId: String
        var externalId: String?
        var properties: [String: SegmentScalar]?
    }

    private let storage: Storage
    private let secure: SecureStore?
    private let logger: UserGistLogger
    private let queue: DispatchQueue
    private var snapshot: Snapshot

    /// Synchronous init: prefers Keychain, falls back to the legacy plaintext
    /// file. After a successful Keychain read we delete the plaintext copy.
    init(storage: Storage, secure: SecureStore?, logger: UserGistLogger, queue: DispatchQueue) {
        self.storage = storage
        self.secure = secure
        self.logger = logger
        self.queue = queue
        if let secure, let raw = secure.read(.identity),
           let existing = try? JSONDecoder.usergist().decode(Snapshot.self, from: raw) {
            self.snapshot = existing
        } else if let legacy = (try? storage.readJSON(Snapshot.self, at: storage.identityFile)) ?? nil {
            // One-time migration from plaintext file → Keychain.
            self.snapshot = legacy
            if let secure, let data = try? JSONEncoder.usergist().encode(legacy),
               secure.write(.identity, data) {
                try? storage.deleteFile(at: storage.identityFile)
            }
        } else {
            self.snapshot = Snapshot(
                anonymousId: Self.generateAnonymousId(),
                externalId: nil,
                properties: nil
            )
            persistInitial()
        }
    }

    private func persistInitial() {
        if let secure, let data = try? JSONEncoder.usergist().encode(snapshot),
           secure.write(.identity, data) {
            return
        }
        // Fallback: plaintext file if Keychain unavailable (e.g. missing
        // entitlement). Best-effort; downstream callers tolerate failure.
        do {
            try storage.writeJSON(self.snapshot, to: storage.identityFile)
        } catch {
            logger.error("failed to persist initial identity", error: error)
        }
    }

    /// Thread-safe read.
    func current() -> Snapshot {
        queue.sync { snapshot }
    }

    var anonymousId: String {
        queue.sync { snapshot.anonymousId }
    }

    func setExternalId(_ externalId: String?) {
        queue.sync {
            guard snapshot.externalId != externalId else { return }
            snapshot.externalId = externalId
            persistLocked()
        }
    }

    @discardableResult
    func mergeProperties(_ properties: [String: Any]?) -> [String: SegmentScalar] {
        queue.sync {
            guard let properties else { return snapshot.properties ?? [:] }
            var next = snapshot.properties ?? [:]
            for (key, value) in properties {
                if let scalar = UserStateTracker.scalar(from: value) {
                    next[key] = scalar
                } else {
                    next.removeValue(forKey: key)
                }
            }
            snapshot.properties = next
            persistLocked()
            return next
        }
    }

    /// Regenerates the anonymous ID and clears the external ID.
    /// Used by `reset()` on user logout.
    func resetAll() {
        queue.sync {
            snapshot = Snapshot(
                anonymousId: Self.generateAnonymousId(),
                externalId: nil,
                properties: nil
            )
            persistLocked()
        }
    }

    private func persistLocked() {
        if let secure, let data = try? JSONEncoder.usergist().encode(snapshot),
           secure.write(.identity, data) {
            return
        }
        // Fallback if Keychain unavailable. Logged as warning so the host
        // can spot missing entitlements without crashing.
        do {
            try storage.writeJSON(snapshot, to: storage.identityFile)
        } catch {
            logger.error("failed to persist identity", error: error)
        }
    }

    private static func generateAnonymousId() -> String {
        let alphabet = Array(
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-"
        )
        var generator = SystemRandomNumberGenerator()
        return String((0..<21).compactMap { _ in alphabet.randomElement(using: &generator) })
    }
}
